### ISSUE TITLE
Can you release the beachmark code?

### ISSUE THREAD

**Issue by LemonQC** [lupantech/IconQA#1]

**Comment by lupantech** [comment]
Yes, the code is coming in weeks

**Comment by LemonQC** [comment]
> 

ok, Thanks. I think this is an interesting work, while the baseline is too high in some tasks, while there may be few attempts

**Comment by lupantech** [comment]
Hi, the code is released just now. Sorry for the delay

**Comment by LemonQC** [comment]
Thanks
